### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by wesleysiqueira** [gosquared/gosquared-rails#10]
When i'm using:
`append_after_action { |controller| controller.add_gosquared_identify_method(current_user) }` 
i receive this error.

invalid byte sequence in UTF-8

**Comment by russellvaughan** [comment]
Hi there, 

Just to follow up here and to provide a bit of context, by adding the append_after_action to the ApplicationController, the intended behaviour is that the GoSquared identify snippet will be added to the body of the response for ALL controllers and ALL actions. 

If your Rails application is not set up so that would be ideal (which looks like that is the case here) you can exclude specific actions in the controllers with an 'except' argument as below 

```
        append_after_action  except: [:action_name_here] do
            |controller| controller.add_gosquared_identify_method current_user
        end

```
   or if you wanted to exclude the whole controller. something like: 

```
 append_after_action  do |controller|
            if (controller.controller_name != 'controller_name_here')
                controller.add_gosquared_identify_method current_user
            end
        end
```

That should solve your issue.

**Comment by wesleysiqueira** [comment]
Second solution worked here!! Thanks !!
